app_name = "san"
data_dir = "sedata"
debug = true
log_dir = "selogs"
llm_model = "sesett"
llm_base_url = "sett"
learning_rate = 1e-4
num_train_epochs = 5

selected_model = "roberta-base"
use_lora = false
[data]
min_word_count = 9
dataset_sample_size = 200000
random_seed = 42
